# Generated by Django 3.0.8 on 2020-09-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200925_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
