# Generated by Django 3.0.8 on 2020-09-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20200925_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_opition', models.CharField(choices=[('cbpay', 'CB Pay'), ('kbzpay', 'KBZ Pay'), ('ayapay', 'AYA Pay'), ('cbbank', 'CB Bank Transfer'), ('kbzbank', 'KBZ Bank Transfer'), ('ayabank', 'AYA Bank Transfer')], max_length=20)),
                ('payment_img', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
