# Generated by Django 3.0.8 on 2020-09-26 08:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200926_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=core.models.Order.get_ref_code, max_length=20, null=True),
        ),
    ]
