# Generated by Django 3.0.8 on 2020-09-28 06:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200926_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_ref_code',
            field=models.CharField(blank=True, default=core.models.Payment.get_ref_code, max_length=20, null=True),
        ),
    ]
