# Generated by Django 3.0.8 on 2020-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201004_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
