# Generated by Django 3.1.2 on 2020-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
