# Generated by Django 3.1.2 on 2020-10-19 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_newsletter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
