# Generated by Django 3.1.2 on 2020-11-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_newsletter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Electronic'), ('S', 'Shirt'), ('U', 'Utility')], max_length=10),
        ),
    ]
